"""Initial ten-table foundation. Preserve vector extension on downgrade."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("product_type IN ('INTERNAL','COMPETITOR')", name=op.f('ck_products_product_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('brand', 'model', name='uq_products_brand_model')
    )
    op.create_index(op.f('ix_products_model'), 'products', ['model'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index('ix_products_type_category', 'products', ['product_type', 'category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN','PRODUCT_MANAGER','SALES')", name=op.f('ck_users_role')),
    sa.CheckConstraint("status IN ('ACTIVE','DISABLED')", name=op.f('ck_users_status')),
    sa.CheckConstraint('token_version >= 0', name=op.f('ck_users_token_version')),
    sa.CheckConstraint('username = lower(username)', name=op.f('ck_users_username_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IN ('SUCCESS','FAILED','DENIED')", name=op.f('ck_audit_logs_result')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_created', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_result_created', 'audit_logs', ['result', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('security_level', sa.String(length=32), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('parse_error', sa.String(length=500), nullable=True),
    sa.Column('upload_user_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('PDF','DOCX','XLSX')", name=op.f('ck_documents_file_type')),
    sa.CheckConstraint("parse_status IN ('UPLOADING','PARSING','READY','FAILED')", name=op.f('ck_documents_parse_status')),
    sa.CheckConstraint("security_level IN ('PUBLIC','INTERNAL','RESTRICTED')", name=op.f('ck_documents_security_level')),
    sa.CheckConstraint('file_size > 0', name=op.f('ck_documents_file_size')),
    sa.ForeignKeyConstraint(['upload_user_id'], ['users.id'], name=op.f('fk_documents_upload_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('file_path', name=op.f('uq_documents_file_path'))
    )
    op.create_index(op.f('ix_documents_security_level'), 'documents', ['security_level'], unique=False)
    op.create_index('ix_documents_status_created', 'documents', ['parse_status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_documents_upload_user_id'), 'documents', ['upload_user_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'CNY'"), nullable=False),
    sa.Column('price_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("price_type IN ('GUIDE','SALES','INTERNAL_QUOTE')", name=op.f('ck_product_prices_price_type')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_product_prices_price_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_prices_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices'))
    )
    op.create_index('ix_product_prices_current', 'product_prices', ['product_id', 'price_type', sa.literal_column('update_time DESC')], unique=False)
    op.create_index('ix_product_prices_update_time', 'product_prices', [sa.literal_column('update_time DESC')], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('row_start', sa.Integer(), nullable=True),
    sa.Column('row_end', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_chunk_index')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_document_chunks_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_product_id'), 'document_chunks', ['product_id'], unique=False)
    op.create_table('document_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN','PRODUCT_MANAGER','SALES')", name=op.f('ck_document_permissions_role')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_permissions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_permissions')),
    sa.UniqueConstraint('document_id', 'role', name='uq_document_permissions_document_role')
    )
    op.create_index('ix_document_permissions_role_document', 'document_permissions', ['role', 'document_id'], unique=False)
    op.create_table('document_products',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_products_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_document_products_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('document_id', 'product_id', name=op.f('pk_document_products'))
    )
    op.create_index('ix_document_products_product_document', 'document_products', ['product_id', 'document_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tool_summary', postgresql.JSONB(astext_type=Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER','ASSISTANT')", name=op.f('ck_messages_role')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    if not op.get_context().as_sql:
        connection = op.get_bind()
        url = connection.engine.url
        database = connection.scalar(sa.text('SELECT current_database()'))
        if database != 'product_agent' or url.host not in ('127.0.0.1', 'localhost') or url.port != 54329:
            raise RuntimeError('Downgrade requires the dedicated local product_agent database on port 54329')
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('document_products')
    op.drop_table('document_permissions')
    op.drop_table('document_chunks')
    op.drop_table('product_prices')
    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
